#!/usr/libexec/platform-python

#
# Copyright (c) 2018 Red Hat, Inc.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
# 02110-1301, USA. 
#

"""
  vdo-by-dev - VDO management by backing device script

  $Id: $

"""

import os
import sys
import subprocess

# Fix up the path to address layout changes
for dir in sys.path:
  vdoDir = os.path.join(dir, 'vdo')
  if os.path.isdir(vdoDir):
    sys.path.append(vdoDir)
    break

from vdomgmnt import *

conf = Configuration("/etc/vdoconf.yml")

rdev = os.stat(sys.argv[1]).st_rdev

# Loop through each VDO in the config and determine whether its backing device
# matches the one provided by the udev trigger (argv[1])
for vdo in conf.getAllVdos().values():
    if os.stat(vdo.device).st_rdev == rdev:
        subprocess.check_call([ "vdo" ] + sys.argv[2:] + [ "--name", vdo.getName() ])

