.TH VDODUMPBLOCKMAP 8 "2023-03-28" "Red Hat" \" -*- nroff -*-
.SH NAME
vdodumpblockmap \- dump the LBA->PBA mappings of a VDO device
.SH SYNOPSIS
.B vdodumpblockmap
.RB [ \-\-lba=\fIlba\fP ]
.I filename
.SH DESCRIPTION
.B vdodumpblockmap
dumps all (or only the specified) LBA->PBA mappings from a cleanly
shut down VDO device.
.PP
.I filename
must be the path of the VDODataLV as described in \fBlvmvdo\fP(7).
.SH OPTIONS
.TP
.B \-\-help
Print this help message and exit.
.TP
.B \-\-lba
Dump only the mapping for the specified LBA.
.TP
.B \-\-version
Show the version of vdodumpblockmap.
.
.SH EXAMPLE
.nf
# lvchange -ay vdo1/vdo0pool_vdata
# vdodumpblockmap /dev/mapper/vdo1-vdo0pool_vdata
# lvchange -an vdo1/vdo0pool_vdata
.fi
.SH SEE ALSO
.BR lvmvdo (7),
.BR lvchange (8)
