.TH VDODMEVENTD 8 "2018-06-12" "Red Hat" \" -*- nroff -*-
.SH NAME
vdodmeventd \- register/unregister a VDO device with dmeventd
.SH SYNOPSIS
.B vdodmeventd
.RI [ options... ]
.I vdo
.SH DESCRIPTION
.B vdodmeventd
handles registration/unregistration by specifying
.I vdo
which is the name of a VDO device. 
.PP
.SH OPTIONS
.TP
.B \-\-help
Print this help message and exit.
.TP
.B \-\-register
Register a VDO device with dmeventd.
.TP
.B \-\-unregister
Unregister a VDO device with dmeventd.
.TP
.B \-\-version
Show the version of vdodmevent.
.
.SH EXAMPLES
.TP
.B vdodmeventd \-\-register\fR is used to register VDO devices.
vdodmeventd \-\-register vdo0
.TP 
.B vdodmeventd \-\-unregister\fR is used to unregister VDO devices.
vdodmeventd \-\-unregister vdo0
.\" .SH NOTES
.SH SEE ALSO
.BR vdo (8).
