.TH VDODUMPMETADATA 8 "2023-03-38" "Red Hat" \" -*- nroff -*-
.SH NAME
vdodumpmetadata \- dump the metadata regions from a VDO device
.SH SYNOPSIS
.B vdodumpmetadata
.RB [ \-\-no\-block\-map ]
.RB [ \-\-lbn=\fIlbn\fP ]
.I vdoBacking outputFile
.SH DESCRIPTION
.B vdodumpmetadata
dumps the metadata regions of a VDO device to
another file, to enable save and transfer of metadata from
a VDO without transfer of the entire backing store.
.PP
.I vdoBacking
must be the path of the VDODataLV as described in \fBlvmvdo\fP(7).
.PP
.B vdodumpmetadata
will produce a large output file. The expected size is
roughly equal to VDO's metadata size. A rough estimate of the storage
needed is 1.4 GB per TB of logical space.
.SH OPTIONS
.TP
\-\-no\-block\-map
Omit the block map. The output file will be of size no higher than
130MB + (9 MB per slab).
.TP
\-\-lbn
Saves the block map page associated with the specified LBN in the
output file. This option may be specified up to 255 times.
Implies \-\-no\-block\-map.
.SH EXAMPLE
.nf
# lvchange -ay vdo1/vdo0pool_vdata
# vdodumpmetadata /dev/mapper/vdo1-vdo0pool_vdata vdo1-meta-dump
# lvchange -an vdo1/vdo0pool_vdata
.fi
.SH SEE ALSO
.BR lvmvdo (7),
.BR lvchange (8),
.BR vdodebugmetadata (8)
