.TH VDOREADONLY 8 "2020-05-13" "Red Hat" \" -*- nroff -*-
.SH NAME
vdoreadonly \- puts a VDO device into read-only mode
.SH SYNOPSIS
.B vdoreadonly
.I filename
.SH DESCRIPTION
.B vdoreadonly
forces an existing VDO device into read-only mode.
.SH OPTIONS
.TP
.B \-\-help
Print this help message and exit.
.TP
.B \-\-version
Show the version of vdoreadonly.
.
.SH SEE ALSO
.BR vdo (8).
