.TH VDOSETUUID 8 "2019-09-12" "Red Hat" \" -*- nroff -*-
.SH NAME
vdosetuuid \- sets a new uuid for the vdo volume stored on a backing
store
.SH SYNOPSIS
.B vdosetuuid
.RI [ options... ]
.I vdoBacking
.SH DESCRIPTION
.B vdosetuuid
sets a new uuid for the VDO volume stored on the 
.I vdoBacking
device, whether the volume is running or not.
.PP
.SH OPTIONS
.TP
.B \-\-help
Print this help message and exit.
.TP
.B \-\-uuid
Sets the uuid value that is stored in the VDO device. If not
specified, the uuid is randomly generated.
.TP
.B \-\-version
Show the version of vdosetuuid.
.SH SEE ALSO
.BR vdo (8).
